//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEngineer.Studio.Extensions.Ichnos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IEngineer.Studio.Extensions.Ichnos.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update Symbol list in the current context. Please update the symbol list when not in a active debug session.
        /// </summary>
        internal static string ErrCannotUpdateSymbolList {
            get {
                return ResourceManager.GetString("ErrCannotUpdateSymbolList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while adding the symbol {0}..
        /// </summary>
        internal static string ErrorAddingSymbol {
            get {
                return ResourceManager.GetString("ErrorAddingSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Evaulate the Symbol {0}..
        /// </summary>
        internal static string ErrorEvaulatingSymbol {
            get {
                return ResourceManager.GetString("ErrorEvaulatingSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ITraceStream is either null or empty. No valid ITraceStream is specified to Trace manager to write trace data. Cannot continue..
        /// </summary>
        internal static string ErrorOutputStreamIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorOutputStreamIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the list of symbols. Symbol Source is either null or Empty.
        /// </summary>
        internal static string ErrorSymbolSourceIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorSymbolSourceIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Unable to get an instance of IVsUIShell. Error messages will not be shown properly.
        /// </summary>
        internal static string ErrorUnableToGetShellInstance {
            get {
                return ResourceManager.GetString("ErrorUnableToGetShellInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception had been thrown by the ITraceListener {0}.
        /// </summary>
        internal static string ErrTraceListenerThrowsExceptionOnWrite {
            get {
                return ResourceManager.GetString("ErrTraceListenerThrowsExceptionOnWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the trace context with the current state of the Environment. A Trace Session is already in progress. Please try when the trace session is completed..
        /// </summary>
        internal static string ErrTraceSessionInProgress {
            get {
                return ResourceManager.GetString("ErrTraceSessionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Trace symbol is not valid in this context. Details :  {0}.
        /// </summary>
        internal static string ErrTraceSymbolInvalid {
            get {
                return ResourceManager.GetString("ErrTraceSymbolInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ichnos (Debug Tracing) Extension for Studio.
        /// </summary>
        internal static string ExtensionTitle {
            get {
                return ResourceManager.GetString("ExtensionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance of the trace manager has already registered for debugger break events.
        /// </summary>
        internal static string MsgAlreadySubscribedForDbgBreak {
            get {
                return ResourceManager.GetString("MsgAlreadySubscribedForDbgBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Event handler for break event is unsubscribed by the trace manager..
        /// </summary>
        internal static string MsgBreakEventHandlerUnsubscribed {
            get {
                return ResourceManager.GetString("MsgBreakEventHandlerUnsubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol Name : {0}, Function Name : {1}, File Name {2}.
        /// </summary>
        internal static string MsgBreakpointContextFormat {
            get {
                return ResourceManager.GetString("MsgBreakpointContextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully subscribed to the Debugger break event.
        /// </summary>
        internal static string MsgDbgBreakEventSubscribeSuccess {
            get {
                return ResourceManager.GetString("MsgDbgBreakEventSubscribeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get  DebuggerEvents Property from DTE.
        /// </summary>
        internal static string MsgDebuggerEventsObjNull {
            get {
                return ResourceManager.GetString("MsgDebuggerEventsObjNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get an instance of DTE. Tracing is impossible. Please report to the extension vendor.
        /// </summary>
        internal static string MsgDTEInitializedFailed {
            get {
                return ResourceManager.GetString("MsgDTEInitializedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Message Pump that processes all the messges and writes them to the listeners is already initialized.
        /// </summary>
        internal static string MsgMessagePumpAlreadyInitialized {
            get {
                return ResourceManager.GetString("MsgMessagePumpAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully returned the list of symbols..
        /// </summary>
        internal static string MsgSymbolsReturnedSuccesfully {
            get {
                return ResourceManager.GetString("MsgSymbolsReturnedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Manager Initialized..
        /// </summary>
        internal static string MsgTraceInitialized {
            get {
                return ResourceManager.GetString("MsgTraceInitialized", resourceCulture);
            }
        }
    }
}
